### ISSUE TITLE
`constituents` input to `write` method of `Bctides` is unused

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/pyschism#102]
In the new API for BCTides, the input for `constituents` is taken (and set to `Tides`) in the `__init__` of `Bctides` class. 
https://github.com/schism-dev/pyschism/blob/f5fa0c26b518632414e033fe3d78d46bb75d891d/pyschism/forcing/bctides/bctides.py#L11-L21
https://github.com/schism-dev/pyschism/blob/f5fa0c26b518632414e033fe3d78d46bb75d891d/pyschism/forcing/bctides/bctides.py#L54

However the `write` method again gets the value of `constituents` and sets it to the `self.constituents` which seems to be unused:
https://github.com/schism-dev/pyschism/blob/f5fa0c26b518632414e033fe3d78d46bb75d891d/pyschism/forcing/bctides/bctides.py#L231-L236
https://github.com/schism-dev/pyschism/blob/f5fa0c26b518632414e033fe3d78d46bb75d891d/pyschism/forcing/bctides/bctides.py#L259-L262

I think the `constituents` argument for `write` method needs to be removed as it is misleading and unused as the constituents are already accounted for in the `Tides` object creation and active ones are taken from there:
https://github.com/schism-dev/pyschism/blob/f5fa0c26b518632414e033fe3d78d46bb75d891d/pyschism/forcing/bctides/bctides.py#L276-L282
.https://github.com/schism-dev/pyschism/blob/f5fa0c26b518632414e033fe3d78d46bb75d891d/pyschism/forcing/bctides/bctides.py#L74
https://github.com/schism-dev/pyschism/blob/f5fa0c26b518632414e033fe3d78d46bb75d891d/pyschism/forcing/bctides/bctides.py#L92
https://github.com/schism-dev/pyschism/blob/f5fa0c26b518632414e033fe3d78d46bb75d891d/pyschism/forcing/bctides/bctides.py#L159

**Comment by cuill** [comment]
@SorooshMani-NOAA Thanks for reviewing the code. I'll modify the code accordingly.

**Comment by SorooshMani-NOAA** [comment]
@cuill no problem! Can you please also release a new version on PyPI either before or after this update? Thanks!

**Comment by SorooshMani-NOAA** [comment]
Since you merged the updates related to this I'm closing this one.
