### ISSUE TITLE
Bug: Incorrect Setting of Number of Tidal Forcing Constituents in bctides.py

### ISSUE THREAD

**Issue by yichengt900** [schism-dev/pyschism#109]
The NOS storm surge team, including @SorooshMani-NOAA, @FariborzDaneshvar-NOAA, and myself, is currently setting up a new SCHISM run with `nwm source relocation` using the most up-to-date pyschism. We have encountered an issue where the `nbfr` parameter is set incorrectly in the bctides.in file when attempting to use all constituents.

Upon investigation, I have identified a bug in the `nbfr` function in [bctides.py](https://github.com/schism-dev/pyschism/blob/06703b9ef88306fccf3e1e0ec0c304302bcdf6d5/pyschism/forcing/bctides/bctides.py#L277C35-L277C35). The correct implementation should be:

`return len(self.tides.get_active_forcing_constituents())`

Instead of the current implementation:

`return len(self.tides.get_active_potential_constituents())`

**Comment by cuill** [comment]
@yichengt900 Thanks for reporting this issue. It has been fixed in the latest release.

**Comment by cuill** [comment]
Please hold on. It failed when publishing to PyPI.
