### ISSUE TITLE
Understanding new changes in the bctides

### ISSUE THREAD

**Issue by BahramKhazaei-NOAA** [schism-dev/pyschism#111]
I used to create bctides using the sample code provided here: https://pyschism.readthedocs.io/en/latest/api/boundary.html#tides-type-3

However, in the new version you can't import **iettype, ifltype, isatype, itetype** anymore:
`from pyschism.forcing.bctides import Bctides, iettype, ifltype, isatype, itetype`

So, basically the error is because the following lines are removed from https://github.com/schism-dev/pyschism/blob/main/pyschism/forcing/bctides/__init__.py:
```python
from pyschism.forcing.bctides.iettype import Iettype
from pyschism.forcing.bctides.ifltype import Ifltype
from pyschism.forcing.bctides.isatype import Isatype
from pyschism.forcing.bctides.itetype import Itetype
from pyschism.forcing.bctides.itrtype import Itrtype
```

Is this a new approach and how do I change the sample code to define **iettype, ifltype, isatype, itetype**?

**Comment by cuill** [comment]
@BahramKhazaei-NOAA The manual for PySCHISM has been incorporated into SCHISM online manual. The one on the readthedocs is no longer updated.

The Bctides API has been changed in the recent release. Arguments **iettype, ifltype, isatype, itetype** are deprecated. Please check SCHISM online manual for updates:
https://schism-dev.github.io/schism/master/getting-started/pre-processing-with-pyschism/bctides.html

**Comment by BahramKhazaei-NOAA** [comment]
@cuill Thank you very much.
