### ISSUE TITLE
Issue with HRRR data from GrADS Data Server 

### ISSUE THREAD

**Issue by cuill** [schism-dev/pyschism#31]
The dataset (https://nomads.ncep.noaa.gov/dods/hrrr) has grid mapping as "linear", not the same as original mapping "lambert_conformal_conic". There are junk values when using hgrid.bbox and meshgrid method.
![Screen Shot 2021-12-17 at 10 23 12 AM](https://user-images.githubusercontent.com/6502663/146586747-da84e0df-0ca4-4c2f-86eb-326258ddf7e8.png)

**Comment by jreniel** [comment]
The two things I would try are:

- bbox_in_hrrr_coords = hgrid.get_boox(crs=HRRR_CRS)
- Crop the array to the minimum rectangle that contains data.

I would probably go for the 2nd option though.

**Comment by cuill** [comment]
The HRRR Zarr format was added as sflux2 under hotstart branch.
