### ISSUE TITLE
Issue with tricontourf for mixed triangular-quadrangular grid

### ISSUE THREAD

**Issue by bkhazaei** [schism-dev/pyschism#37]
I try to plot the bathymetry for Delaware Domain based the following schism function:
```
hgrid = Hgrid.open(PathToGrid + 'hgrid.gr3', crs='EPSG:4326')
hgrid.tricontourf(axes=ax, levels=50, vmin=vmin, vmax=vmax, cmap='jet')
```
However, the quadrangular portion of the grid is not plotted as follows:
![image](https://user-images.githubusercontent.com/60622555/165989633-4649aa9e-464c-43ba-b8d0-0ac1cb2c6691.png)

One possible solution is to:

```
hgrid = Hgrid.open(PathToGrid + 'hgrid.gr3', crs='EPSG:4326')
hgrid.tricontourf(axes=ax, levels=50, vmin=vmin, vmax=vmax, cmap='jet')
hgrid.quadface(axes=ax, cmap='jet')
```
But the quadface function does not take levels, vmin, and vmax arguments so the figure will look like:
![image](https://user-images.githubusercontent.com/60622555/165989990-47fee311-5936-41fa-9ed0-5cf366ca306a.png)

Is there a solution for this?

**Comment by jamal919** [comment]
A quick solution could be to use this script - https://github.com/schism-dev/schism/blob/master/src/Utility/Pre-Processing/split_quads_wwm.f90 - to create a pure tri connectivity-table, and plot it. 

Long solution is to implement the fortran script into the toolbox, and call this transformation when tricontourf is called.

**Comment by jreniel** [comment]
`plt.triplot(hgrid.elements.triangulation)`

**Comment by bkhazaei** [comment]
Thanks Jaime @jreniel, that solved my problem!
