### ISSUE TITLE
Add support for parametric wind setup

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/pyschism#38]
Recently SCHISM has added Holland model support. It would be nice if we could set it up using `PySCHISM` by either providing a `deck b` file directly or by passing in the hurricane identifiers to fetch the info using `StormEvents` or something similar to it.

**Comment by SorooshMani-NOAA** [comment]
@cuill do you currently have plans for adding this? If not, I can start looking into adding it. If I want to develop, what it the current strategy for branching? Should I branch off of `main`, `develop` or `hotstart`?

**Comment by cuill** [comment]
@SorooshMani-NOAA This task is delayed because of other priorities at the moment. I have merged the hotstart branch into the main. So it should be fine if you branch off the main and work on it. Thanks.
