### ISSUE TITLE
`pyschism` requires internet connection to be able to import it

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/pyschism#49]
I get connection error when I try to import `pyschism` submodules on a compute node, because it doesn't have internet connection.
e.g. trying to import `Hgrid` from `pyschism.mesh` results in `pyschism.__init__` to be called which imports `ModelDriver` and `ModelConfig` which subsequently try to load `param.opt`; importing `opt.py` requires an Internet connection due to the fact that it tries to download template file for `param.nml` from GitHub at the module level: 
https://github.com/schism-dev/pyschism/blob/96e52fd54ff9beacc5e30e7fe2821989d0b67bd4/pyschism/param/opt.py#L15
This results in a call to:
https://github.com/schism-dev/pyschism/blob/96e52fd54ff9beacc5e30e7fe2821989d0b67bd4/pyschism/param/schism_init.py#L148-L152
which results in connection error.

**Comment by jreniel** [comment]
https://github.com/schism-dev/pyschism/pull/54
