### ISSUE TITLE
Inconsistency in model inputs longitude range using ERA5 forcing function

### ISSUE THREAD

**Issue by BahramKhazaei-NOAA** [schism-dev/pyschism#67]
I converted an ADCIRC grid into a SCHISM grid using pyschism functions simply using:
```
from pyschism.mesh.hgrid import Hgrid
m = Hgrid.open("address/to/fort.14")
m.write("address/to/grd3file.gr3", format="gr3", overwrite=True)
```
In the original ADCIRC mesh the lon values range between [0,360], resulting in SCHISM **hgrid.gr3** and **windrot.gr3** to be in the same range.

However, due to the following lines in the [ERA5](https://github.com/schism-dev/pyschism/blob/fc6675391fa97e708a47b6ac9d38cbf8567af53c/pyschism/forcing/nws/nws2/era5.py) function:

```python
        for x in self.lon:
            if x > 180:
                lon.append(x-360)
            else:
                lon.append(x)
```

the resulting forcing NC files will have lon attribute in range [-180, 180]. That causes an inconsistency in the model and makes it crash. So, I believe that adding the above lines in the py, schism functions to make that translation at hgrid calculation/preparation will resolve that issue and will keep the lon range in [-180, 180] for the entire pre-processing steps.

**Comment by BahramKhazaei-NOAA** [comment]
How about the forcing data? Can SCHISM take forcing data in range [0,360]? If so, I recommend the above constraint is removed from the ERA5 function, so that it doesn't force the met input files to be in [-180, 180] range.

**Comment by josephzhang8** [comment]
Yes sflux is part of the inputs. It can be [0,360] (as we did in Pacifc setup).

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by cuill** [comment]
The longitude conversion has been removed for ERA5 in the latest pyschism.

**Comment by BahramKhazaei-NOAA** [comment]
Great. I will close the issue then. Thanks!
