### ISSUE TITLE
Question: NWM historical data

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/pyschism#89]
@cuill if I setup a retrospective run e.g. Florence 2018 using `pyschism`. For NWM forcing will I get the then-forecasts at the time of the storm or I'll get latest hindcast reanalysis for NWM?

**Comment by cuill** [comment]
@SorooshMani-NOAA 
You'll get retrospective dataset:
https://github.com/schism-dev/pyschism/blob/7b71ae9687a66f2d49af48844b960a1d99869dc9/pyschism/forcing/source_sink/nwm.py#L389

**Comment by SorooshMani-NOAA** [comment]
I see, thanks!
