### ISSUE TITLE
installation issue with pyschism

### ISSUE THREAD

**Issue by zduvims** [schism-dev/pyschism#90]
Have anyone tried to install pyschism to a defined conda environment on a Mac M1 chip?

I used conda to create a new environment and activated it. However, if I use
`pip install -e .`
The package was always installed in my python 3.11 folder.

I have to use the below method to successfully install to a conda environment.
` python -m pip install -e . `

I'm not sure if this is an issue with the M1 chip, but I have had some similar situations before.

**Comment by pmav99** [comment]
It's unlikely that this is related to the CPU architecture.

Open a new console, activate the conda env and run:
```
which python
which pip
```
Do they point to the same directory? If yes, then everything is fine and somehow your $PATH was messed up. If not then you need to tell us how you installed pip. Normally it comes from conda.

**Comment by zduvims** [comment]
> It's unlikely that this is related to the CPU architecture.
> 
> Open a new console, activate the conda env and run:
> 
> ```
> which python
> which pip
> ```
> 
> Do they point to the same directory? If yes, then everything is fine and somehow your $PATH was messed up. If not then you need to tell us how you installed pip. Normally it comes from conda.

They do not point to the same directory...
I modified ~/.zshrc and ~/.bash_profile, and the problem was fixed. Thank you!
