### ISSUE TITLE
the problems of useing pyschism

### ISSUE THREAD

**Issue by hb-9797** [schism-dev/pyschism#91]
Sir,I'm a python newbie,and I create a new environment in conda, And successfully installed pyschism (according to the installation instructions), pyschism can be seen in the conda environment. Use it in pycharm and use the corresponding interpreter, but still have the following problem: ModuleNotFoundError: No module named 'appdirs', is there a way to fix this?
Thanks! 

![image](https://github.com/schism-dev/pyschism/assets/129708252/b84b0a36-9438-4b0b-bd34-8df976d4bce4)

![image](https://github.com/schism-dev/pyschism/assets/129708252/d4250ef1-e6a0-460a-a388-0cdc3cefe16f)

**Comment by SorooshMani-NOAA** [comment]
@hb-9797 you should be able to install `appdirs` using either conda or pip in your environment. If you're using a terminal to install packages, call: `pip install appdirs`.

@cuill I think we need to add `appdirs` to the project requirement in the `setup.py` file. So let's keep this ticket open until we do so

**Comment by hb-9797** [comment]
> @hb-9797 you should be able to install using either conda or pip in your environment. If you're using a terminal to install packages, call: .`appdirs``pip install appdirs`
> 
> @cuill I think we need to add to the project requirement in the file. So let's keep this ticket open until we do so`appdirs``setup.py`

thanks，I installed the appdirs package, but a new error was reported:
**`FileNotFoundError:` cfunits requires UNIDATA UDUNITS-2. Can't find the 'udunits2' library. ,** 
I tried to install udunites2, but found that the information given on the Internet is basically in R. This puts me in a difficult situation, have you also encountered this problem?

**Comment by SorooshMani-NOAA** [comment]
I guess the requirement list of `pyschism` needs some more update. In any case, you should be able to install `udunits2` in your environment using either conda or pip. I'd suggest using conda (when your environment is activated):
```
conda install -cconda-forge udunits2
```
It might later also complain about `cfgrib` or `cfunits`, `hdf5`, and `netcdf4` as well, so you can basically install all using conda:
```
conda install -cconda-forge hdf5 netcdf4 udunits2 cfgrib cfunits appdirs
```

**Comment by cuill** [comment]
@SorooshMani-NOAA Sure. I've been tied up with the STOFS3D annual upgrade and will fix this issue maybe next week.

**Comment by SorooshMani-NOAA** [comment]
@cuill there's no rush, I just tagged you since you're the main person maintaining `pyschism`. 😃

**Comment by hb-9797** [comment]
> I guess the requirement list of `pyschism` needs some more update. In any case, you should be able to install `udunits2` in your environment using either conda or pip. I'd suggest using conda (when your environment is activated):
> 
> ```
> conda install -cconda-forge udunits2
> ```
> 
> It might later also complain about `cfgrib` or `cfunits`, `hdf5`, and `netcdf4` as well, so you can basically install all using conda:
> 
> ```
> conda install -cconda-forge hdf5 netcdf4 udunits2 cfgrib cfunits appdirs
> ```
Thanks for your help, based on the errors and prompts, I installed a few of the libraries you mentioned (and checked in conda that they were indeed successfully installed), however, there is still an error reported but it only prompts for:
**ImportError:` cannot import name 'Hgrid' from 'pyschism' `(E:\APPs\Annconda3-2021.11\envs\pyschism\lib\site-packages\pyschism\__init__.py)**
which is a bit of a struggle as someone new to python for a short while.

PS:I have previously been using matlab to produce the files needed for schism, but recently I have been getting anomalous simulation results and have been unable to get better results after several tweaks, so I would like to use pyschism to check if there is something wrong with the production files.
![image](https://github.com/schism-dev/pyschism/assets/129708252/03d353d9-ca77-4c7f-ac77-dcbb7866b1a2)

**Comment by SorooshMani-NOAA** [comment]
@hb-9797 you need to import `Hgrid` from `pyschism.mesh` **not** `pyschism`:

```python
from pyschim.mesh import Hgrid
```

**Comment by hb-9797** [comment]
helpful!
