### ISSUE TITLE
Problem about the windrot

### ISSUE THREAD

**Issue by Caizhiwen19901122** [schism-dev/pyschism#95]
When I try to obtain the windrot_geo2proj.gr3 file, an error occurs as:  TypeError: __init__() missing 1 required positional argument: 'nodes'

The code is:
from datetime import datetime
from time import time
import pathlib

from pyschism.forcing.nws.nws2.era5 import ERA5
from pyschism.forcing.nws.nws2.nws2 import NWS2

from pyschism.mesh.hgrid import Hgrid
from pyschism.mesh.gridgr3 import Windrot
from pyschism.mesh.base import Gr3

if __name__ == '__main__':

    startdate=datetime(2018, 1, 1)
    rnday=5

    t0=time()
    hgrid = Gr3.open('./hgrid.gr3', crs='epsg:4326')
    bbox = hgrid.get_bbox('EPSG:4326', output_type='bbox')
    windrot=Windrot().default(hgrid=Hgrid)

**Comment by SorooshMani-NOAA** [comment]
@Caizhiwen19901122 when you want to create the wind rotation object from the grid, you should call it like
```python
hgrid = Hgrid.open('./hgrid.gr3', crs='epsg:4326')
windrot = Windrot.default(hgrid=hgrid)
```
Note that:
- there are no parentheses immediately after `Windrot`
- you need to pass the `hgrid` object to the `default` method, and not the `Hgrid` class. 
- I'm using `Hgrid` class to open the grid file. `Hgrid` is a class that inherits `Gr3` class and has boundary definition capability too
