### ISSUE TITLE
Question: Tools for inspecting NWM input files

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/pyschism#98]
Are there any utility functions available on `pyschism` to inspect the generated input files for NWM? 
There seems to be some Matlab scripts on SCHISM repo, are such tools available as a part of pyschism too?

**Comment by cuill** [comment]
@SorooshMani-NOAA 
This is not implemented in pyshcism. But pylib has this feature (not only for source/sink, also support checking for other inputs):
https://schism-dev.github.io/schism/master/getting-started/pre-processing-with-pylib/schismcheck.html

**Comment by SorooshMani-NOAA** [comment]
I see, thank you
